### ISSUE TITLE
feat: add GitHub Actions Workflow for deployment to Dokploy

### ISSUE THREAD

**Issue by vilhelmprytz** [kthaisociety/backend#31]
We should create a GitHub Actions Workflow that triggers deployment to our Dokploy instance.

```yaml
name: Dokploy Deployment Workflow

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dokploy Deployment
      uses: benbristow/dokploy-deploy-action@0.0.1
      with:
        auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
        application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
        dokploy_url: ${{ secrets.DOKPLOY_URL }}
```
